java_library(name = 'graphjet',
  dependencies = [
    '3rdparty/jvm/org/slf4j:slf4j-api',
    '3rdparty/jvm/org/slf4j:slf4j-jdk14',
    'science/src/java/com/twitter/graphjet/algorithms',
    'science/src/java/com/twitter/graphjet/bipartite',
    'science/src/java/com/twitter/graphjet/hashing',
    'science/src/java/com/twitter/graphjet/math',
    'science/src/java/com/twitter/graphjet/stats',
  ],
  sources = globs('*.java'),
  description='A super target for all the folders in the graph directory.'
)
