junit_tests(name = 'algorithms',
  dependencies = [
    '3rdparty/jvm/junit',
    'science/src/java/com/twitter/graphjet/algorithms',
    'science/src/java/com/twitter/graphjet/bipartite',
    'science/src/java/com/twitter/graphjet/hashing',
  ],
  sources = rglobs('*.java')
)
