junit_tests(name = 'bipartite',
  dependencies = [
    '3rdparty/jvm/junit',
    '3rdparty/jvm/org/apache/commons:commons-lang3',
    'science/src/java/com/twitter/graphjet/bipartite',
  ],
  sources = rglobs('*.java')
)
