junit_tests(name = 'hashing',
  dependencies = [
    '3rdparty/jvm/com/google/guava:guava',
    '3rdparty/jvm/junit',
    'science/src/java/com/twitter/graphjet/bipartite/api',
    'science/src/java/com/twitter/graphjet/hashing',
  ],
  sources = rglobs('*.java')
)

