junit_tests(name = 'graphjet',
  dependencies = [
    'science/tests/java/com/twitter/graphjet/algorithms',
    'science/tests/java/com/twitter/graphjet/bipartite',
    'science/tests/java/com/twitter/graphjet/hashing',
    'science/tests/java/com/twitter/graphjet/math',
  ],
  sources = rglobs('*.java'),
  known_to_fail = 'SD-5815'
)
