java_library(name = 'math',
  dependencies = [
    '3rdparty/jvm/it/unimi/dsi:fastutil',
  ],
  sources = globs('*.java'),
  provides = artifact(
    org = 'com.twitter.graphjet',
    name = 'math',
    repo = artifactory,
  ),
  description='A math util package for graphs.'
)
